version: '3.8'

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:24.3.6.48-alpine
    container_name: clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse-data:/var/lib/clickhouse
      - ./config.xml:/etc/clickhouse-server/users.d/config.xml
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ''
      CLICKHOUSE_DB: default

volumes:
  clickhouse-data: